### ISSUE TITLE
Add a better way to know if an event is a comment or not.

### ISSUE THREAD

**Issue by ArjixWasTaken** [chireiden/python-ass#15]
Currently as far as I know we have to do the following:
```python
import ass

file = "example.ass"

with open(file, encoding='utf_8_sig') as f:
    doc = ass.parse(f)

for event in doc.events:
    if isinstance(event, ass.line.Comment):
        print("this is a comment:", event)
```

there should be a better way to identify if an event is a comment or not, like a property in the class

**Comment by ArjixGamer** [comment]
a property like ``isComment: bool`` would do the job i think
so we could do ``if event.isComment:``

**Comment by FichteFoll** [comment]
You can also use `event.TYPE == "Comment"`, although I don't like that interface at all and would like to remove or deprecate it in a potential refactoring. 

So far, we have avoided breaking changes since taking over maintenance and at this point I'm not even sure we should do that at all instead of building a new ASS library from the ground up. This decition will likely depend on how much would need to be refactored.

**Comment by ArjixGamer** [comment]
oh, there was that way as well?
didnt notice
