### ISSUE TITLE
`Tag` class cannot be instantiated → remove it

### ISSUE THREAD

**Issue by integralAva** [chireiden/python-ass#22]
### Issue
问题出在`self.params`上
类的初始化函数中不包含属性`param`，在后文中无法被引用
若在初始化函数中声明该属性，此方法即可正常使用

### Origin
`self.param = params`

<img width="480" alt="image" src="https://github.com/chireiden/python-ass/assets/114299643/881f37f6-1dbf-455c-8264-0ea2719a2481">

### It should be...
`self.params = params`

<img width="486" alt="image" src="https://github.com/chireiden/python-ass/assets/114299643/720d4daa-b857-4f3e-a06c-3dbc954ed472">

**Comment by FichteFoll** [comment]
Thanks for the report, although I don't understand Chinese. However, the screenshots were helpful enough.

Funnily, this actually [has never worked ever since the `Tag` class was added](https://github.com/chireiden/python-ass/commit/e3d7d0e9e0fa9c3eaaa4324eb651db92a12650aa) and since I don't like the current version of it anyway (the readme defers to another tag parsing library, for example), I'll use this as an excuse to remove this code entirely.
